services:

  cache:
    ports:
      - 6379:6379

  firebird_ara:
    image: jacobalberty/firebird
    container_name: firebird_ara
    hostname: firebird
    environment:
      FIREBIRD_DATABASE: "CLIPP_ARA.FDB"
      FIREBIRD_USER: "SYSDBA"
      ISC_PASSWORD: "masterkey"
    ports:
       - 3051:3050
    restart: always
    volumes:
      - $PWD/infra/fdb:/firebird/data/
    networks:
      - infra
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  firebird_cwb:
    image: jacobalberty/firebird
    container_name: firebird_cwb
    hostname: firebird
    environment:
      FIREBIRD_DATABASE: "CLIPP_CWB.FDB"
      FIREBIRD_USER: "SYSDBA"
      ISC_PASSWORD: "masterkey"
    ports:
       - 3052:3050
    restart: always
    volumes:
      - $PWD/infra/fdb:/firebird/data/
    networks:
      - infra
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  firebird_lon:
    image: jacobalberty/firebird
    container_name: firebird_lon
    hostname: firebird
    environment:
      FIREBIRD_DATABASE: "CLIPP_LON.FDB"
      FIREBIRD_USER: "SYSDBA"
      ISC_PASSWORD: "masterkey"
    ports:
       - 3053:3050
    restart: always
    volumes:
      - $PWD/infra/fdb:/firebird/data/
    networks:
      - infra
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  firebird_nat:
    image: jacobalberty/firebird
    container_name: firebird_nat
    hostname: firebird
    environment:
      FIREBIRD_DATABASE: "CLIPP_NAT.FDB"
      FIREBIRD_USER: "SYSDBA"
      ISC_PASSWORD: "masterkey"
    ports:
       - 3054:3050
    restart: always
    volumes:
      - $PWD/infra/fdb:/firebird/data/
    networks:
      - infra
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  firebird_rec:
    image: jacobalberty/firebird
    container_name: firebird_rec
    hostname: firebird
    environment:
      FIREBIRD_DATABASE: "CLIPP_REC.FDB"
      FIREBIRD_USER: "SYSDBA"
      ISC_PASSWORD: "masterkey"
    ports:
       - 3055:3050
    restart: always
    volumes:
      - $PWD/infra/fdb:/firebird/data/
    networks:
      - infra
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"


  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    ports:
      - 27017:27017
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      # - $PWD/infra/mongodb/db:/data/db:rw
      # - $PWD/infra/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

      - $PWD/infra/mongodb/mongod.conf:/etc/mongod.conf
      - $PWD/infra/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
      - $PWD/infra/mongodb/data/db/:/data/db/:rw
      - $PWD/infra/mongodb/data/log/:/var/log/mongodb/:rw
    restart: always
    networks:
      - infra
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"


  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    # volumes:
    #   - $PWD/infra/mongo-express/docker-entrypoint.sh:/docker-entrypoint.sh
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 0
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${MONGO_ROOT_PASSWORD}
      # ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      # ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_LOGIN}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD}
    depends_on:
      - mongodb
    restart: always
    networks:
      - infra
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
