version: "3.8"

services:

  # cache:
  #   image: redis:alpine
  #   container_name: cache
  #   hostname: cache
  #   volumes:
  #     - $PWD/infra/redis/data:/var/lib/redis
  #   networks:
  #     - infra
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "5"

  osservice:
    stdin_open: true
    tty: true
    image: wborbajr/osservice:latest
    container_name: osservice
    hostname: osservice
    build:
      context: .
      dockerfile: dockerfile/Dockerfile
    # volumes:
    #   - $PWD/.:/osservice:rw
    working_dir: /osservice/app
    # depends_on:
    #   - cache
    init: true
    restart: always
    # env_file:
    #   - .env
    environment:
      - TZ=America/Sao_Paulo
      - LC_CTYPE=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      # - APP_PORT=2021
      # - ARA="SYSDBA:masterkey@127.0.0.1:3051//firebird/data/CLIPP_ARA.FDB?charset=WIN1252"
      # - CWB="SYSDBA:masterkey@127.0.0.1:3052//firebird/data/CLIPP_CWB.FDB?charset=WIN1252"
      # - LON="SYSDBA:masterkey@127.0.0.1:3053//firebird/data/CLIPP_LON.FDB?charset=WIN1252"
      # - NAT="SYSDBA:masterkey@127.0.0.1:3054//firebird/data/CLIPP_NAT.FDB?charset=WIN1252"
      # - REC="SYSDBA:masterkey@127.0.0.1:3055//firebird/data/CLIPP_REC.FDB?charset=WIN1252"
    networks:
      - infra
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  infra:
    driver: bridge
