version: "3.8"

services:

  firebird:
    image: jacobalberty/firebird
    container_name: firebird
    hostname: firebird
    ports:
       - 3050:3050
    restart: always
    volumes:
      - $PWD/fdb:/firebird/data/
    networks:
      - infra
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  osservice:
    stdin_open: true
    tty: true
    container_name: ${CONTAINER}
    hostname: ${PROJECT_NAME}
    image: ${DOCKER_USER}/${PROJECT_NAME}:${DOCKER_TAG}
    build:
      context: .
      dockerfile: dockerfile/Dockerfile
    volumes:
      - $PWD/.:/osservice:rw
    # depends_on:
    #   - database
    networks:
      - infra
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  infra:
    driver: bridge