version: "3.8"

services:

  osservice:
    stdin_open: true
    tty: true
    image: wborbajr/osservice:latest
    container_name: osservice
    hostname: osservice
    build:
      context: .
      dockerfile: ./dockerfile.prod/Dockerfile
    working_dir: /osservice/app
    depends_on:
      - cache
    init: true
    restart: always
    environment:
      - TZ=America/Sao_Paulo
      - LC_CTYPE=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
    networks:
      - infra
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  cache:
    image: redis:alpine
    container_name: cache
    hostname: cache
    volumes:
      - $PWD/infra/redis/data:/var/lib/redis
    networks:
      - infra
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  infra:
    driver: bridge



