version: "3.8"

services:

  firebird_ara:
    image: jacobalberty/firebird
    container_name: firebird_ara
    hostname: firebird
    environment:
      FIREBIRD_DATABASE: "CLIPP_ARA.FDB"
      FIREBIRD_USER: "SYSDBA"
      ISC_PASSWORD: "masterkey"
      # - FIREBIRD_USER:SYSDBA
      # - FIREBIRD_PASSWORD:masterkey
    ports:
       - 3051:3050
    restart: always
    volumes:
      - $PWD/infra/fdb:/firebird/data/
      # - $PWD/fbconf/SYSDBA.password:/firebird/etc/
      # - $PWD/fbconf/firebird.conf:/firebird/etc/
    networks:
      - infra
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  firebird_cwb:
    image: jacobalberty/firebird
    container_name: firebird_cwb
    hostname: firebird
    environment:
      FIREBIRD_DATABASE: "CLIPP_CWB.FDB"
      FIREBIRD_USER: "SYSDBA"
      ISC_PASSWORD: "masterkey"
      # - FIREBIRD_USER:SYSDBA
      # - FIREBIRD_PASSWORD:masterkey
    ports:
       - 3052:3050
    restart: always
    volumes:
      - $PWD/infra/fdb:/firebird/data/
      # - $PWD/fbconf/SYSDBA.password:/firebird/etc/
      # - $PWD/fbconf/firebird.conf:/firebird/etc/
    networks:
      - infra
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  firebird_lon:
    image: jacobalberty/firebird
    container_name: firebird_lon
    hostname: firebird
    environment:
      FIREBIRD_DATABASE: "CLIPP_LON.FDB"
      FIREBIRD_USER: "SYSDBA"
      ISC_PASSWORD: "masterkey"
      # - FIREBIRD_USER:SYSDBA
      # - FIREBIRD_PASSWORD:masterkey
    ports:
       - 3053:3050
    restart: always
    volumes:
      - $PWD/infra/fdb:/firebird/data/
      # - $PWD/fbconf/SYSDBA.password:/firebird/etc/
      # - $PWD/fbconf/firebird.conf:/firebird/etc/
    networks:
      - infra
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  firebird_nat:
    image: jacobalberty/firebird
    container_name: firebird_nat
    hostname: firebird
    environment:
      FIREBIRD_DATABASE: "CLIPP_NAT.FDB"
      FIREBIRD_USER: "SYSDBA"
      ISC_PASSWORD: "masterkey"
      # - FIREBIRD_USER:SYSDBA
      # - FIREBIRD_PASSWORD:masterkey
    ports:
       - 3054:3050
    restart: always
    volumes:
      - $PWD/infra/fdb:/firebird/data/
      # - $PWD/fbconf/SYSDBA.password:/firebird/etc/
      # - $PWD/fbconf/firebird.conf:/firebird/etc/
    networks:
      - infra
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  firebird_rec:
    image: jacobalberty/firebird
    container_name: firebird_rec
    hostname: firebird
    environment:
      FIREBIRD_DATABASE: "CLIPP_REC.FDB"
      FIREBIRD_USER: "SYSDBA"
      ISC_PASSWORD: "masterkey"
      # - FIREBIRD_USER:SYSDBA
      # - FIREBIRD_PASSWORD:masterkey
    ports:
       - 3055:3050
    restart: always
    volumes:
      - $PWD/infra/fdb:/firebird/data/
      # - $PWD/fbconf/SYSDBA.password:/firebird/etc/
      # - $PWD/fbconf/firebird.conf:/firebird/etc/
    networks:
      - infra
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"



  osservice:
    stdin_open: true
    tty: true
    container_name: ${CONTAINER}
    hostname: ${PROJECT_NAME}
    image: ${DOCKER_USER}/${PROJECT_NAME}:${DOCKER_TAG}
    build:
      context: .
      dockerfile: dockerfile/Dockerfile
    volumes:
      - $PWD/.:/osservice:rw
    # depends_on:
    #   - database
    init: true
    restart: always
    environment:
      - TZ=America/Sao_Paulo
      - LC_CTYPE=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
    networks:
      - infra
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  infra:
    driver: bridge