version: "3.8"

services:

  osservice:
    environment:
      - FEATURE_TOGGLE=TRUE
      - APP_PORT=3001
      - ARA="SYSDBA:masterkey@127.0.0.1:3051//firebird/data/CLIPP_ARA.FDB?charset=WIN1252"
      - CWB="SYSDBA:masterkey@127.0.0.1:3052//firebird/data/CLIPP_CWB.FDB?charset=WIN1252"
      - LON="SYSDBA:masterkey@127.0.0.1:3053//firebird/data/CLIPP_LON.FDB?charset=WIN1252"
      - NAT="SYSDBA:masterkey@127.0.0.1:3054//firebird/data/CLIPP_NAT.FDB?charset=WIN1252"
      - REC="SYSDBA:masterkey@127.0.0.1:3055//firebird/data/CLIPP_REC.FDB?charset=WIN1252"
    ports:
      - "3001:3001"

  cache:
    ports:
      - 6379:6379

  firebird_ara:
    image: jacobalberty/firebird
    container_name: firebird_ara
    hostname: firebird
    environment:
      FIREBIRD_DATABASE: "CLIPP_ARA.FDB"
      FIREBIRD_USER: "SYSDBA"
      ISC_PASSWORD: "masterkey"
    ports:
       - 3051:3050
    restart: always
    volumes:
      - $PWD/infra/fdb:/firebird/data/
    networks:
      - infra
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  firebird_cwb:
    image: jacobalberty/firebird
    container_name: firebird_cwb
    hostname: firebird
    environment:
      FIREBIRD_DATABASE: "CLIPP_CWB.FDB"
      FIREBIRD_USER: "SYSDBA"
      ISC_PASSWORD: "masterkey"
    ports:
       - 3052:3050
    restart: always
    volumes:
      - $PWD/infra/fdb:/firebird/data/
    networks:
      - infra
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  firebird_lon:
    image: jacobalberty/firebird
    container_name: firebird_lon
    hostname: firebird
    environment:
      FIREBIRD_DATABASE: "CLIPP_LON.FDB"
      FIREBIRD_USER: "SYSDBA"
      ISC_PASSWORD: "masterkey"
    ports:
       - 3053:3050
    restart: always
    volumes:
      - $PWD/infra/fdb:/firebird/data/
    networks:
      - infra
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  firebird_nat:
    image: jacobalberty/firebird
    container_name: firebird_nat
    hostname: firebird
    environment:
      FIREBIRD_DATABASE: "CLIPP_NAT.FDB"
      FIREBIRD_USER: "SYSDBA"
      ISC_PASSWORD: "masterkey"
    ports:
       - 3054:3050
    restart: always
    volumes:
      - $PWD/infra/fdb:/firebird/data/
    networks:
      - infra
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  firebird_rec:
    image: jacobalberty/firebird
    container_name: firebird_rec
    hostname: firebird
    environment:
      FIREBIRD_DATABASE: "CLIPP_REC.FDB"
      FIREBIRD_USER: "SYSDBA"
      ISC_PASSWORD: "masterkey"
    ports:
       - 3055:3050
    restart: always
    volumes:
      - $PWD/infra/fdb:/firebird/data/
    networks:
      - infra
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
