name: Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  check:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Start infrastructure
      run: docker-compose up -d

    - name: Dispose infrastructure
      run: docker-compose down
